# Generated by Django 6.0.1 on 2026-02-14 15:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AddrLine1_Value', models.CharField(blank=True, max_length=500)),
                ('AddrLine2_Value', models.CharField(blank=True, max_length=500)),
                ('AddrLine3_Value', models.CharField(blank=True, max_length=500)),
                ('AddressID_Value', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('AddressType_Value', models.CharField(blank=True, max_length=500)),
                ('City_Value', models.CharField(blank=True, max_length=500)),
                ('Country_Value', models.CharField(blank=True, max_length=500)),
                ('County_Value', models.CharField(blank=True, max_length=500)),
                ('Description_Value', models.CharField(blank=True, max_length=500)),
                ('StateProvince_Value', models.CharField(blank=True, max_length=500)),
                ('ZipPostalCode_Value', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AlternativeIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description_Value', models.CharField(blank=True, max_length=500)),
                ('Identifier_Value', models.CharField(blank=True, max_length=500)),
                ('IdentifierType_Value', models.CharField(choices=[('Other', 'Other'), ('UUID', 'UUID'), ('UPC', 'UPC'), ('ProdCode', 'ProdCode'), ('LEI', 'Legal Entity Identifier'), ('PEN', 'Private Enterprise Number'), ('DID', 'Decentralized Identifier'), ('DUNS', 'DUNS'), ('DPP_EU', 'EU Digital Product Passport'), ('FEIN', 'Federal Employer Identification Number'), ('UEI', 'Unique Entity Identifier')], max_length=8)),
                ('SourceName_Value', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(blank=True, max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description_Value', models.CharField(blank=True, max_length=500)),
                ('Email_Value', models.EmailField(blank=True, max_length=254)),
                ('EntityRole_Value', models.CharField(choices=[('Originator', 'Originator'), ('Installer', 'Installer'), ('AuthorityHavingJurisdiction', 'Authority Having Jurisdiction (AHJ)'), ('Manufacturer', 'Manufacturer'), ('Surety', 'Surety'), ('Insurer', 'Insurer'), ('TestLab', 'Test Lab'), ('CertificationAgency', 'Certification Agency'), ('Aggregator', 'Aggregator'), ('PropertyOwner', 'Property Owner'), ('Financier', 'Financier'), ('QualifyingAgency', 'Qualifying Agency')], max_length=27)),
                ('LegalEntityIdentifier_Value', models.CharField(blank=True, max_length=20)),
                ('TaxID_Value', models.CharField(blank=True, max_length=50)),
                ('URL_Value', models.URLField(blank=True)),
                ('WorkPhone_Value', models.CharField(blank=True, max_length=15)),
                ('Addresses', models.ManyToManyField(to='server.address')),
                ('AlternativeIdentifiers', models.ManyToManyField(to='server.alternativeidentifier')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactID_Value', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ContactType_Value', models.CharField(choices=[('Other', 'Other'), ('FireMarshal', 'FireMarshal'), ('Owner', 'Owner'), ('OffTaker', 'OffTaker'), ('Inspector', 'Inspector'), ('Engineer', 'Engineer'), ('Originator', 'Originator'), ('Installer', 'Installer'), ('Investor', 'Investor'), ('PermittingOfficial', 'PermittingOfficial'), ('ProjectManager', 'ProjectManager'), ('Salesperson', 'Salesperson'), ('ReportPreparer', 'ReportPreparer'), ('Referrer', 'Referrer'), ('Security', 'Security'), ('Safety', 'Safety'), ('Technician', 'Technician'), ('Occupant', 'Occupant')], max_length=18)),
                ('Description_Value', models.CharField(blank=True, max_length=500)),
                ('Email_Value', models.EmailField(blank=True, max_length=254)),
                ('FirstName_Value', models.CharField(blank=True, max_length=500)),
                ('HomePhone_Value', models.CharField(blank=True, max_length=15)),
                ('LastName_Value', models.CharField(blank=True, max_length=500)),
                ('MiddleName_Value', models.CharField(blank=True, max_length=500)),
                ('MobilePhone_Value', models.CharField(blank=True, max_length=15)),
                ('PreferredContactMethod_Value', models.CharField(choices=[('Email', 'Email'), ('WorkPhone', 'WorkPhone'), ('CellPhone', 'CellPhone'), ('HomePhone', 'HomePhone'), ('CellTextMessage', 'CellTextMessage')], max_length=15)),
                ('Timezone_Value', models.CharField(blank=True, max_length=500)),
                ('Title_Value', models.CharField(blank=True, max_length=500)),
                ('URL_Value', models.URLField(blank=True)),
                ('WorkPhone_Value', models.CharField(blank=True, max_length=15)),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.address')),
            ],
        ),
        migrations.CreateModel(
            name='CreditRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreditScore_Value', models.CharField(blank=True, max_length=500)),
                ('CreditScoreSource_Value', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Altitude_Unit', models.CharField(choices=[('ft', 'Foot'), ('in', 'Inch'), ('mi', 'Mile'), ('nmi', 'Nautical Mile'), ('yd', 'Yard'), ('cm', 'Centimetre'), ('dm', 'Decimetre'), ('km', 'Kilometre'), ('m', 'Metre'), ('mm', 'Millimetre')], max_length=3)),
                ('Altitude_Value', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('Description_Value', models.CharField(blank=True, max_length=500)),
                ('Elevation_Unit', models.CharField(choices=[('ft', 'Foot'), ('in', 'Inch'), ('mi', 'Mile'), ('nmi', 'Nautical Mile'), ('yd', 'Yard'), ('cm', 'Centimetre'), ('dm', 'Decimetre'), ('km', 'Kilometre'), ('m', 'Metre'), ('mm', 'Millimetre')], max_length=3)),
                ('Elevation_Value', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('Latitude_Unit', models.CharField(choices=[('Degree', 'Degree'), ('rad', 'Radian')], max_length=6)),
                ('Latitude_Value', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('LocationDeterminationMethod_Value', models.CharField(choices=[('Unknown', 'Unknown'), ('GPS', 'GPS'), ('Survey', 'Survey'), ('AerialImage', 'AerialImage'), ('EngineeringReport', 'EngineeringReport'), ('AddressGeocoding', 'AddressGeocoding')], max_length=17)),
                ('LocationID_Value', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('LocationType_Value', models.CharField(choices=[('DeviceSpecific', 'DeviceSpecific'), ('SiteEntrance', 'SiteEntrance'), ('GeneralProximity', 'GeneralProximity'), ('Warehouse', 'Warehouse')], max_length=16)),
                ('Longitude_Unit', models.CharField(choices=[('Degree', 'Degree'), ('rad', 'Radian')], max_length=6)),
                ('Longitude_Value', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(blank=True, max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistTemplateMaintainer',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.entity')),
                ('ChecklistTemplateMaintainerID_Value', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ChecklistTemplateMaintainerName_Value', models.CharField(blank=True, max_length=500)),
            ],
            bases=('server.entity',),
        ),
        migrations.AddField(
            model_name='entity',
            name='Contacts',
            field=models.ManyToManyField(to='server.contact'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentDate_Value', models.DateTimeField(blank=True, null=True)),
                ('CommentID_Value', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('CommentText_Value', models.CharField(blank=True, max_length=500)),
                ('Contacts', models.ManyToManyField(to='server.contact')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='CreditRatings',
            field=models.ManyToManyField(to='server.creditrating'),
        ),
        migrations.AddField(
            model_name='address',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.location'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentMethodName_Value', models.CharField(blank=True, max_length=500)),
                ('PaymentToken_Value', models.CharField(blank=True, max_length=500)),
                ('AlternativeIdentifiers', models.ManyToManyField(to='server.alternativeidentifier')),
                ('Comments', models.ManyToManyField(to='server.comment')),
                ('Tags', models.ManyToManyField(to='server.tag')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='PaymentMethods',
            field=models.ManyToManyField(to='server.paymentmethod'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnswerRangeMax_Value', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('AnswerRangeMin_Value', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('AnswerType_Value', models.CharField(choices=[('Text', 'Text'), ('EnumeratedSingle', 'EnumeratedSingle'), ('EnumeratedMultiple', 'EnumeratedMultiple'), ('Numeric', 'Numeric'), ('Date', 'Date'), ('URL', 'URL'), ('File', 'File')], max_length=18)),
                ('DisplaySeqNumber_Value', models.IntegerField(blank=True, null=True)),
                ('QuestionHelp_Value', models.CharField(blank=True, max_length=500)),
                ('QuestionID_Value', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('QuestionLabel_Value', models.CharField(blank=True, max_length=500)),
                ('QuestionUnits_Value', models.CharField(blank=True, max_length=500)),
                ('RequirementLevel_Value', models.CharField(choices=[('Required', 'Required'), ('Optional', 'Optional'), ('ConditionallyRequired', 'ConditionallyRequired')], max_length=21)),
                ('RequirementNotes_Value', models.CharField(blank=True, max_length=500)),
                ('SectionName_Value', models.CharField(blank=True, max_length=500)),
                ('AnswerOptions', models.ManyToManyField(to='server.answeroption')),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description_Value', models.CharField(blank=True, max_length=500)),
                ('FileFolderURL_Value', models.URLField(blank=True)),
                ('ScopeID_Value', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ScopeType_Value', models.CharField(choices=[('Project', 'Project'), ('PVSystem', 'PVSystem'), ('Site', 'Site'), ('Device', 'Device'), ('Portfolio', 'Portfolio'), ('GeoRegion', 'GeoRegion'), ('Task', 'Task'), ('Assembly', 'Assembly'), ('Component', 'Component')], max_length=9)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.location')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.scope'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Tags',
            field=models.ManyToManyField(to='server.tag'),
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChecklistTemplateID_Value', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ChecklistTemplateName_Value', models.CharField(blank=True, max_length=500)),
                ('ChecklistTemplateVersion_Value', models.CharField(blank=True, max_length=500)),
                ('Description_Value', models.CharField(blank=True, max_length=500)),
                ('Questions', models.ManyToManyField(to='server.question')),
                ('Tags', models.ManyToManyField(to='server.tag')),
                ('ChecklistTemplateMaintainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.checklisttemplatemaintainer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ChecklistTemplateID_Value', 'ChecklistTemplateVersion_Value'), name='unique_checklist_template_id_version')],
            },
        ),
    ]
